[package]
name = "poker-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "1.0"
poker-core = { path = "../poker-core" }
diesel = { version = "1.0", features = ["sqlite"] }
dotenv = "*"