name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Update
      run: rustup update; rustup component add rustfmt; rustup component add clippy

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Run manual-game tests
      run: cd tests/manual-game && make --keep-going

    - name: Run web-integration tests
      run: cd tests/web-integration && make --keep-going

    - name: Fail on lacking fmt.
      run: rustfmt --check 
    
    - name: Cargo Clippy
      run: cargo clippy -- -D warnings
